### ISSUE TITLE
What's the different between using this package and localeCompare?

### ISSUE THREAD

**Issue by setkyar** [mapmeld/myanmar-sort#3]
Hi,

I am checking this package to help contribute, I don't understand what's different between `localeCompare`? Can you explain me?

```
['က', 'ခ'].sort((a, b) => a.localeCompare(b));
```

**Comment by mapmeld** [comment]
Mingalaba @setkyar - I am not sure!

I know that it is difficult to sort Burmese names and words correctly (one reference: http://blog.saturngod.net/knowledgebase/myanmar-unicode-sorting-with-swift ).  I wrote this in 2015 because I read that blog post and Intl.Collator was not available in Node.

I know that ```burmese_words.sort()``` (without custom function) or SQL ```SORT BY``` does not work.

Instead of  အ, အု, ေအ, ေအာ, ေအာ္, အံ, အို , using localeCompare on my machine I got အ,အံ,အို,အု,ေအ,ေအာ,ေအာ္

**If localeCompare sorts words correctly, please use it.** . But it differs from @saturngod advice there

Also if you are sorting names, be sure to remove U / Daw / Doctor before sorting, myanmar-names uses this package for that

**Comment by setkyar** [comment]
Hi @mapmeld , thanks for the clarification.
